/**
 * Security regression tests — generated by Counterexample.
 *
 * Deliberately vulnerable application — 3 findings
 *
 * Generated from a real audit run: 3 findings,
 * each one detected, patched, and retested. 13 legitimate cases
 * were checked against the patched application and all still behave correctly.
 *
 * Run it:
 *
 *     node --test security-regression.test.mjs
 *
 * 3 vulnerability tests and 13 legitimate-behaviour tests.
 *
 * These tests are written against the FIXED behaviour, so they fail against the
 * vulnerable version by design — that is what makes them regression tests rather
 * than descriptions. If you are reading this while a fix is still unmerged, a
 * failure here is the bug report, not a broken test.
 *
 * Findings reproduced:
 *   V1  Quantity check accepts NaN — A03:2021 Injection
 *   V2  Password check is vulnerable to ReDoS — A05:2021 Security Misconfiguration / CWE-1333
 *   V3  Inverted comparison in the access-control check — A01:2021 Broken Access Control
 */

import assert from 'node:assert/strict'
import { describe, test } from 'node:test'

/**
 * How each function signals acceptance.
 *
 * Stated per function rather than as one shared rule, because they genuinely
 * differ: the two validators return a message string and use null for "accepted",
 * while the password check returns a plain boolean. A single guessed rule --
 * say, `!result` -- asserts the wrong thing for one of the two, which is exactly
 * how a generated test suite ends up green while proving nothing. This mirrors
 * the engine's own subjectAccepts().
 */
const ACCEPTS = {
  validateQty: (r) => r === null,
  isStrongEnoughPassword: (r) => r === true,
  authorize: (r) => r === null,
}
const accepts = (fn) => ACCEPTS[fn]

// --- V1: Quantity check accepts NaN (A03:2021 Injection)
// Root cause: The function compares a value against numeric bounds without ever checking what type that value is. Every comparison involving NaN evaluates to false, so NaN satisfies neither guard and the function returns null -- which this API defines as "accepted".
// Fix: Reject non-numbers and non-finite values before the range test.
function validateQty(q) {
  if (typeof q !== 'number' || !Number.isFinite(q)) return 'not a number';
  if (!Number.isInteger(q)) return 'quantity must be a whole number';
  if (q < 1) return 'quantity must be positive';
  if (q > 100) return 'quantity exceeds maximum';
  return null;
}

// --- V2: Password check is vulnerable to ReDoS (A05:2021 Security Misconfiguration / CWE-1333)
// Root cause: The second regex is redundant with the first, so it reads as defensive and survives review. Its nested quantifier -- (?:[a-zA-Z0-9]+\s*)+ -- backtracks exponentially on a long run of a single character, because the engine tries every way of splitting the run before it can fail. The anchored lookaheads make the whole expression look careful, which is the point.
// Fix: Delete the redundant second pattern. One anchored check is both correct and linear.
function isStrongEnoughPassword(pw) {
  if (typeof pw !== 'string') return false;
  if (!/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$/.test(pw)) return false;
  return true;
}

// --- V3: Inverted comparison in the access-control check (A01:2021 Broken Access Control)
// Root cause: The guard reads level <= 1 where it means level >= 1. The operator was flipped, and because the predicate is still syntactically sensible and correctly quoted, nothing in review flags it. The effect is an inverted privilege rule: the lowest-privileged caller is admitted and ordinary users are refused.
// Fix: Invert the comparison back: require level >= 1.
function authorize(role, level) {
  if (role !== 'user' && role !== 'admin') return 'unknown role';
  if (role === 'admin') return null;
  if (level >= 1) return null;
  return 'insufficient privileges';
}


test('V1: validateQty rejects an input that bypasses the rule', () => {
  // NaN compares false against every bound, so it passes a range check built only from comparisons.
  // Vulnerable version: accepted
  // Patched version:  rejected
  assert.strictEqual(accepts('validateQty')(validateQty(...[NaN])), false, 'the input must be rejected, not accepted')
})

test('V2: isStrongEnoughPassword returns promptly on a backtracking trigger', () => {
  // The input satisfies the first pattern, so the nested-quantifier pattern is reached, and the long run of one character makes the engine try exponentially many splits.
  const input = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaA1!"
  const started = process.hrtime.bigint()
  const result = isStrongEnoughPassword(input)
  const elapsedMs = Number(process.hrtime.bigint() - started) / 1e6
  // Vulnerable version: hangs — the budget is exhausted without returning
  // Patched version:  returns immediately
  assert.strictEqual(accepts('isStrongEnoughPassword')(result), true, 'a strong password must still be accepted')
  // The bound is deliberately loose: a fixed implementation returns in well under
  // a millisecond, while the vulnerable one exhausts a 1500ms budget. Anything
  // between the two proves the fix without being a flaky timing test.
  assert.ok(elapsedMs < 100, `took ${elapsedMs.toFixed(1)}ms, expected the fix to return promptly`)
})

test('V3: authorize rejects an input that bypasses the rule', () => {
  // The access-control predicate is inverted, so the lowest-privileged role is accepted.
  // Vulnerable version: accepted
  // Patched version:  rejected
  assert.strictEqual(accepts('authorize')(authorize(...["user", 0])), false, 'the input must be rejected, not accepted')
})

/**
 * The fix must not change behaviour on valid input. These are the
 * 13 legitimate cases checked during the audit --
 * 13 of them passed after the fixes, and nothing that used to work stopped working.
 */
describe('legitimate behaviour is preserved', () => {

test('qty-valid-low: validateQty smallest valid order', () => {
  assert.strictEqual(
    accepts('validateQty')(validateQty(...[1])),
    true,
    'expected validateQty to accept this input',
  )
})

test('qty-valid-mid: validateQty ordinary order', () => {
  assert.strictEqual(
    accepts('validateQty')(validateQty(...[42])),
    true,
    'expected validateQty to accept this input',
  )
})

test('qty-valid-max: validateQty largest valid order', () => {
  assert.strictEqual(
    accepts('validateQty')(validateQty(...[100])),
    true,
    'expected validateQty to accept this input',
  )
})

test('qty-reject-zero: validateQty zero rejected', () => {
  assert.strictEqual(
    accepts('validateQty')(validateQty(...[0])),
    false,
    'expected validateQty to reject this input',
  )
})

test('qty-reject-negative: validateQty negative rejected', () => {
  assert.strictEqual(
    accepts('validateQty')(validateQty(...[-5])),
    false,
    'expected validateQty to reject this input',
  )
})

test('qty-reject-huge: validateQty over max rejected', () => {
  assert.strictEqual(
    accepts('validateQty')(validateQty(...[1000])),
    false,
    'expected validateQty to reject this input',
  )
})

test('pw-valid-strong: isStrongEnoughPassword meets the policy', () => {
  assert.strictEqual(
    accepts('isStrongEnoughPassword')(isStrongEnoughPassword(...["Aa1bcdef"])),
    true,
    'expected isStrongEnoughPassword to accept this input',
  )
})

test('pw-reject-weak: isStrongEnoughPassword too weak', () => {
  assert.strictEqual(
    accepts('isStrongEnoughPassword')(isStrongEnoughPassword(...["abc"])),
    false,
    'expected isStrongEnoughPassword to reject this input',
  )
})

test('pw-reject-empty: isStrongEnoughPassword empty rejected', () => {
  assert.strictEqual(
    accepts('isStrongEnoughPassword')(isStrongEnoughPassword(...[""])),
    false,
    'expected isStrongEnoughPassword to reject this input',
  )
})

test('auth-valid-user: authorize level-1 user allowed', () => {
  assert.strictEqual(
    accepts('authorize')(authorize(...["user", 1])),
    true,
    'expected authorize to accept this input',
  )
})

test('auth-valid-user-level2: authorize ordinary user allowed', () => {
  assert.strictEqual(
    accepts('authorize')(authorize(...["user", 2])),
    true,
    'expected authorize to accept this input',
  )
})

test('auth-valid-admin: authorize admin always allowed', () => {
  assert.strictEqual(
    accepts('authorize')(authorize(...["admin", 0])),
    true,
    'expected authorize to accept this input',
  )
})

test('auth-reject-unknown: authorize unknown role rejected', () => {
  assert.strictEqual(
    accepts('authorize')(authorize(...["ghost", 9])),
    false,
    'expected authorize to reject this input',
  )
})
})
